### ISSUE TITLE
Violaessence Ban Appeal (Please Read)

### ISSUE THREAD

**Issue by Violaessence** [drewhoener/SimpleWiki#1]
Hello there, I cannot register to the forums however i am wondering if i can make a ban appeal somehow, I am sorry for my actions and I own up to them, I don't have an excuse for them and won't make one, I was just a royal ass and I deserved to be banned, Please could I have another shot at playing on Johnnywoof?

**Comment by drewhoener** [comment]
1: Not the place for this
2: Forum logs show that you didn't even TRY to make an account, that's where we handle ban appeals now, you'll need to try to log on & view your ban message to get your signup token for the forums.
3: Still not the place for this. If you want to appeal on the forums you can, but again, not the place

**Comment by Violaessence** [comment]
The problem is i can't do ./register on the server and that is required in the sign up process i have tried signing up

**Comment by drewhoener** [comment]
No. It's not. Go and try to log in, the ban message will display your token and then you can sign up. This was intentional so that people that are banned can access their token. Have a good night
